export default [
  {
    login: 'strafe',
    id: 15663890,
    node_id: 'MDQ6VXNlcjE1NjYzODkw',
    avatar_url: 'https://avatars0.githubusercontent.com/u/15663890?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/strafe',
    html_url: 'https://github.com/strafe',
    followers_url: 'https://api.github.com/users/strafe/followers',
    following_url: 'https://api.github.com/users/strafe/following{/other_user}',
    gists_url: 'https://api.github.com/users/strafe/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/strafe/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/strafe/subscriptions',
    organizations_url: 'https://api.github.com/users/strafe/orgs',
    repos_url: 'https://api.github.com/users/strafe/repos',
    events_url: 'https://api.github.com/users/strafe/events{/privacy}',
    received_events_url: 'https://api.github.com/users/strafe/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cucicivan',
    id: 44273991,
    node_id: 'MDQ6VXNlcjQ0MjczOTkx',
    avatar_url: 'https://avatars1.githubusercontent.com/u/44273991?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cucicivan',
    html_url: 'https://github.com/cucicivan',
    followers_url: 'https://api.github.com/users/cucicivan/followers',
    following_url:
      'https://api.github.com/users/cucicivan/following{/other_user}',
    gists_url: 'https://api.github.com/users/cucicivan/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/cucicivan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cucicivan/subscriptions',
    organizations_url: 'https://api.github.com/users/cucicivan/orgs',
    repos_url: 'https://api.github.com/users/cucicivan/repos',
    events_url: 'https://api.github.com/users/cucicivan/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/cucicivan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cucic98',
    id: 46110246,
    node_id: 'MDQ6VXNlcjQ2MTEwMjQ2',
    avatar_url: 'https://avatars2.githubusercontent.com/u/46110246?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cucic98',
    html_url: 'https://github.com/cucic98',
    followers_url: 'https://api.github.com/users/cucic98/followers',
    following_url:
      'https://api.github.com/users/cucic98/following{/other_user}',
    gists_url: 'https://api.github.com/users/cucic98/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cucic98/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cucic98/subscriptions',
    organizations_url: 'https://api.github.com/users/cucic98/orgs',
    repos_url: 'https://api.github.com/users/cucic98/repos',
    events_url: 'https://api.github.com/users/cucic98/events{/privacy}',
    received_events_url: 'https://api.github.com/users/cucic98/received_events',
    type: 'User',
    site_admin: false,
  },
];
