export default {
  login: 'daliboru',
  id: 44033510,
  node_id: 'MDQ6VXNlcjQ0MDMzNTEw',
  avatar_url: 'https://avatars1.githubusercontent.com/u/44033510?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/daliboru',
  html_url: 'https://github.com/daliboru',
  followers_url: 'https://api.github.com/users/daliboru/followers',
  following_url: 'https://api.github.com/users/daliboru/following{/other_user}',
  gists_url: 'https://api.github.com/users/daliboru/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/daliboru/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/daliboru/subscriptions',
  organizations_url: 'https://api.github.com/users/daliboru/orgs',
  repos_url: 'https://api.github.com/users/daliboru/repos',
  events_url: 'https://api.github.com/users/daliboru/events{/privacy}',
  received_events_url: 'https://api.github.com/users/daliboru/received_events',
  type: 'User',
  site_admin: false,
  name: 'Dalibor Belic',
  company: null,
  blog: 'www.daliborbelic.com',
  location: 'Novi Sad',
  email: null,
  hireable: null,
  bio: 'Entrepreneur & Developer',
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 3,
  following: 0,
  created_at: '2018-10-10T16:32:11Z',
  updated_at: '2021-01-11T23:24:38Z',
};
